# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_city',
            field=models.CharField(blank=True, choices=[('1', 'Freshman'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior'), ('5', 'Graduate')], max_length=1),
        ),
    ]
