# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_primary_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_city',
            field=models.CharField(blank=True, choices=[('BA', 'Bath'), ('BN', 'Brighton'), ('BS', 'Bristol'), ('CB', 'Cambridge'), ('EH', 'Edinburgh'), ('L', 'London'), ('M', 'Manchester'), ('OX', 'Oxford')], max_length=255),
        ),
    ]
