# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20170717_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_line_one',
            field=models.CharField(default='13 Bath House', max_length=200),
            preserve_default=False,
        ),
    ]
