# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_address_line_one'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_line_one',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_bedroom',
            field=models.IntegerField(default=0, verbose_name='Number of Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_feet',
            field=models.IntegerField(default=0, verbose_name='Square Feet'),
        ),
    ]
