# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_address_line_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_check_in', models.DateTimeField(verbose_name='check in date')),
                ('date_of_check_out', models.DateTimeField(verbose_name='check out date')),
                ('guest_name', models.CharField(max_length=200)),
                ('booking_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
    ]
